//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_ventas.datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cliente
    {
        public tbl_cliente()
        {
            this.tbl_factura = new HashSet<tbl_factura>();
        }
    
        public string id_cliente { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string empresa { get; set; }
        public string direccion { get; set; }
        public string cuidad { get; set; }
        public string tipo { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
    
        public virtual ICollection<tbl_factura> tbl_factura { get; set; }
    }
}
