//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_ventas.datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_usuarios
    {
        public tbl_usuarios()
        {
            this.tbl_compras = new HashSet<tbl_compras>();
            this.tbl_factura = new HashSet<tbl_factura>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string clave { get; set; }
        public string rol { get; set; }
    
        public virtual ICollection<tbl_compras> tbl_compras { get; set; }
        public virtual ICollection<tbl_factura> tbl_factura { get; set; }
    }
}
