//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_ventas.datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_producto
    {
        public tbl_producto()
        {
            this.tbl_compras = new HashSet<tbl_compras>();
            this.tbl_factura = new HashSet<tbl_factura>();
        }
    
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string marca { get; set; }
        public int id_clasificacion { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento { get; set; }
        public string descripcion { get; set; }
        public decimal precio { get; set; }
    
        public virtual ICollection<tbl_compras> tbl_compras { get; set; }
        public virtual ICollection<tbl_factura> tbl_factura { get; set; }
    }
}
